# Generated by Django 4.1.3 on 2024-01-31 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='', max_length=50)),
                ('post_content', models.CharField(default='', max_length=400)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(default='', max_length=400)),
                ('categories', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musiccityapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=20)),
                ('image_url', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musiccityapi.post')),
                ('reaction_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musiccityapi.reaction')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musiccityapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musiccityapi.user'),
        ),
    ]
