# Generated by Django 4.1.3 on 2024-02-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiccityapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreaction',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postreaction',
            old_name='reaction_id',
            new_name='reaction',
        ),
        migrations.RenameField(
            model_name='postreaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
