# Generated by Django 4.1.3 on 2024-02-07 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiccityapi', '0002_rename_post_id_postreaction_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='musiccityapi.post'),
        ),
    ]
